### ISSUE TITLE
Object Browser

### ISSUE THREAD

**Issue by nicholasammann** [playmer/YTE#232]
Convert to new framework, split functionality correctly between Object Browser widget and ObjectTree.

**Comment by playmer** [comment]
So...I didn't split these things into a Tree and a Browser. I kept it unified for now, as I ran into issues with layouting the ObjectTree inside the CompositionBrowser (I renamed the ObjectBrowser), plus I wasn't satisfied with the exisiting separation of concerns (which is my fault, the refactor was unfinished when I picked it up, and in my rush to complete it I didn't finish understand/finish this piece when I was working on it). I'll close this and leave a future refactor issue for either Nick or I to do if we so desire..
