### ISSUE TITLE
Wwise is not wworking

### ISSUE THREAD

**Issue by kstrebel** [playmer/YTE#247]
- [ ] Update Wwise to latest version 
- [ ] Update .wproj and .akbank (?) files to newest version

**Comment by playmer** [comment]
We at least found the correct WWise version this week: Wwise 2017.1.0.6340

**Comment by playmer** [comment]
WWise has been separated out into it's own Repo and it is correctly documented with the version we used in LambPlanet. We can look at updating those in the appropriate repos.
